import { createChannel } from '../src/audio/engine';
import { crossGains,cutoff } from '../src/domain/session';
function wave(buffer:AudioBuffer){const data=buffer.getChannelData(0),bytes=new ArrayBuffer(44+data.length*2),v=new DataView(bytes);function text(offset:number,t:string){for(let i=0;i<t.length;i++)v.setUint8(offset+i,t.charCodeAt(i));}text(0,'RIFF');v.setUint32(4,bytes.byteLength-8,true);text(8,'WAVEfmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,buffer.sampleRate,true);v.setUint32(28,buffer.sampleRate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);text(36,'data');v.setUint32(40,data.length*2,true);data.forEach((n,i)=>v.setInt16(44+i*2,Math.round(Math.max(-1,Math.min(1,n))*32767),true));return bytes;}
async function render(gain:number,filter:number,treble=0){const ctx=new OfflineAudioContext(1,24000,24000),channel=createChannel(ctx,ctx.destination);channel.eq.high.gain.value=treble;channel.gain.gain.value=gain;channel.filter.frequency.value=cutoff(filter);const osc=ctx.createOscillator();osc.frequency.value=4000;osc.connect(channel.filter);osc.start();return (await ctx.startRendering()).getChannelData(0);}
const rms=(a:Float32Array)=>Math.sqrt(a.reduce((s,v)=>s+v*v,0)/a.length);
document.getElementById('run')!.onclick=async()=>{try{
 const cutHigh=rms(await render(.8,1,-12));
 const open=rms(await render(.8,1)),muted=rms(await render(0,1)),dark=rms(await render(.8,0));if(!(open>.3&&cutHigh<open*.6&&muted===0&&dark<open*.02))throw new Error('Routing/filter assertion failed');
 const ctx=new OfflineAudioContext(1,12*24000,24000),master=ctx.createGain();master.gain.value=.5;master.connect(ctx.destination);const channels=[createChannel(ctx,master),createChannel(ctx,master)];
 for(const [i,id]of ['amber','afterglow'].entries())for(const stem of ['drums','bass','melody']){const buffer=await ctx.decodeAudioData(await(await fetch(`/audio/${id}-${stem}.wav`)).arrayBuffer());const s=ctx.createBufferSource();s.buffer=buffer;s.connect(channels[i].filter);s.start(i===0?0:4);}
 for(let n=0;n<=80;n++){const [a,b]=crossGains(n/80),t=4+n/20;channels[0].gain.gain.linearRampToValueAtTime(a*.8,t);channels[1].gain.gain.linearRampToValueAtTime(b*.8,t);}channels[0].gain.gain.setValueAtTime(.8,0);channels[1].gain.gain.setValueAtTime(0,0);channels[1].filter.frequency.setValueAtTime(20000,9);channels[1].filter.frequency.exponentialRampToValueAtTime(160,10);
 const audio=await ctx.startRendering(),data=audio.getChannelData(0);let peak=0;for(const x of data)peak=Math.max(peak,Math.abs(x));if(peak>=1||rms(data)<.01)throw new Error('Fixture render empty or clipped');
 const blob=new Blob([wave(audio)],{type:'audio/wav'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='offline-booth-transition.wav';link.textContent='Download 12-second audio evidence';document.getElementById('evidence')!.replaceChildren(link);const player=document.createElement('audio');player.controls=true;player.src=url;document.getElementById('evidence')!.append(player);
 document.getElementById('results')!.textContent=JSON.stringify({passed:true,trebleCutRMS:cutHigh,openRMS:open,mutedRMS:muted,darkRMS:dark,fixtureRMS:rms(data),peak,checks:['actual gain routing','low-pass attenuation','six decoded fixture stems','equal-power handoff','non-silent unclipped mix'],sequence:'0–4 A; 4–8 A→B; 9–10 B filter closes; 10–12 dark B'},null,2);
 }catch(e){document.getElementById('results')!.textContent=String(e);}};
