import { test,expect } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
test('play, rerender, missing Astra, filter, pause/cue and reset',async({page,request})=>{
 await page.goto('/');await page.getByRole('button',{name:'Start audio',exact:false}).click();await page.getByRole('button',{name:'Track library & accessible controls',exact:false}).click();await page.getByRole('button',{name:'Play A',exact:true}).click();await expect(page.getByLabel('Deck A position')).toContainText('playing');
 await page.waitForTimeout(1200);const before=await page.getByLabel('Deck A position').textContent();expect(parseFloat(before!)).toBeGreaterThan(.5);
 await page.getByLabel('Filter A',{exact:true}).fill('0.2');await page.getByRole('button',{name:'Track library & accessible controls',exact:false}).click();await page.getByRole('button',{name:'Track library & accessible controls',exact:false}).click();expect(parseFloat((await page.getByLabel('Deck A position').textContent())!)).toBeGreaterThan(parseFloat(before!));
 const status=await request.get('/api/status');const s=await status.json();if(!s.available){const response=await request.post('/api/hint',{data:{}});expect(response.status()).toBe(401);await expect(page.getByLabel('Deck A position')).toContainText('playing');}
 await page.getByRole('button',{name:'Pause A',exact:true}).click();const paused=await page.getByLabel('Deck A position').textContent();await page.waitForTimeout(300);expect(await page.getByLabel('Deck A position').textContent()).toBe(paused);
 await page.getByRole('button',{name:'Cue A',exact:true}).click();await expect(page.getByLabel('Deck A position')).toContainText('0.00');await page.getByRole('button',{name:'Start practice',exact:true}).click();await expect(page.getByLabel('Filter A',{exact:true})).toHaveValue('1');await expect(page.getByLabel('Crossfader',{exact:true})).toHaveValue('0');await expect(page.getByLabel('Deck B position')).toContainText('0.00');await page.getByRole('button',{name:'Stop all decks',exact:false}).click();
});
test('actual OfflineAudioContext verifies routing and exports audio',async({page})=>{await page.goto('/tests/audio.html');await page.getByRole('button',{name:'Render & verify'}).click();await expect(page.locator('#results')).toContainText('"passed": true');const download=page.waitForEvent('download');await page.getByRole('link',{name:'Download 12-second audio evidence'}).click();await(await download).saveAs('docs/evidence/offline-booth-transition.wav');await writeFile('docs/evidence/audio-check.json',(await page.locator('#results').textContent())!);});
test('complete a live timed handoff and capture actual engine output',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Start audio',exact:false}).click();await page.getByRole('button',{name:'Track library & accessible controls',exact:false}).click();
 await page.getByRole('button',{name:'Capture mix',exact:false}).click();await page.getByRole('button',{name:'Start practice',exact:true}).click();
 // Use the instrument shortcut for the timed entry. Scrolling the off-screen
 // accessible Play B button into view adds unrelated automation latency.
 await page.locator('.canvas-host canvas').focus();
 await expect.poll(async()=>parseFloat((await page.getByLabel('Deck A position').textContent())!),{intervals:[20],timeout:12000}).toBeGreaterThanOrEqual(7.88);
 await page.keyboard.press('p');await page.getByLabel('Crossfader',{exact:true}).fill('0.5');await page.waitForTimeout(1800);await page.getByLabel('Crossfader',{exact:true}).fill('1');
 await expect(page.getByLabel('Transition practice')).toContainText('Timing objective complete.');await page.waitForTimeout(600);await page.getByRole('button',{name:'Finish capture',exact:false}).click();
 const link=page.getByRole('link',{name:'Save audio',exact:false});await expect(link).toBeVisible();
 const url=(await link.getAttribute('href'))!;const metrics=await page.evaluate(async(url)=>{const bytes=await(await fetch(url)).arrayBuffer(),ctx=new OfflineAudioContext(1,24000,24000),buffer=await ctx.decodeAudioData(bytes);let peak=0,sum=0;const samples=buffer.getChannelData(0);for(const x of samples){peak=Math.max(peak,Math.abs(x));sum+=x*x;}return {duration:buffer.duration,peak,rms:Math.sqrt(sum/samples.length),sampleRate:buffer.sampleRate};},url);
 expect(metrics.duration).toBeGreaterThan(9);expect(metrics.rms).toBeGreaterThan(.01);expect(metrics.peak).toBeLessThan(1);await writeFile('docs/evidence/live-capture-check.json',JSON.stringify(metrics,null,2));
 const download=page.waitForEvent('download');await link.click();await(await download).saveAs('docs/evidence/live-booth-handoff.webm');await page.getByRole('button',{name:'Stop all decks',exact:false}).click();await page.getByRole('button',{name:'Track library & accessible controls',exact:false}).click();await page.screenshot({path:'docs/evidence/practice-complete.png',fullPage:true});
});
test('import has unknown analysis, can play, and retry restores fixtures',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Start audio',exact:false}).click();await page.getByRole('button',{name:'Track library & accessible controls',exact:false}).click();await page.getByLabel('Load deck B').setInputFiles('public/audio/amber.wav');await expect(page.getByText('local import · analysis unknown',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Play B',exact:true}).click();await expect(page.getByLabel('Deck B position')).toContainText('playing');await page.getByRole('button',{name:'Start practice',exact:true}).click();await expect(page.getByRole('heading',{name:'Deck B Afterglow Steps'})).toBeVisible();await expect(page.getByLabel('Deck B position')).toContainText('0.00');
});
