import { expect, test } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';

test.beforeEach(async ({ page }) => {
 await page.route('**/api/library', route => route.fulfill({ json: { tracks: [] } }));
 await mkdir('docs/evidence/experience', { recursive: true });
});

test('Afterhours accepts an existing name without generating one and shares only the accepted name', async ({ page }) => {
 const outgoing: string[] = [];
 page.on('request', request => outgoing.push(request.url() + (request.postData() || '')));
 await page.goto('/#advanced/name');
 await expect(page.getByRole('button', { name: 'Enter my name', exact: true })).toHaveAttribute('aria-pressed', 'true');
 await expect(page.getByLabel('High school mascot')).toHaveCount(0);
 const name = page.getByRole('textbox', { name: 'Your name or DJ name', exact: true });
 await name.fill('   ');
 await expect(page.getByRole('button', { name: 'Continue to music →' })).toBeDisabled();
 await name.fill('  Velvet   Atlas  ');
 await page.screenshot({ path: 'docs/evidence/experience/afterhours-enter-name.png' });
 await name.press('Enter');
 await expect(page).toHaveURL(/#advanced\/session$/);
 await expect(page.getByRole('heading', { name: 'Velvet Atlas', exact: true })).toBeVisible();
 await expect(page.getByRole('heading', { name: 'Build your crate.' })).toBeVisible();
 await page.getByRole('button', { name: 'Change DJ name' }).click();
 await expect(name).toHaveValue('Velvet Atlas');
 await name.fill('Unsaved Encore');
 await page.getByRole('button', { name: 'Keep Velvet Atlas & continue →' }).click();
 await expect(page.getByRole('heading', { name: 'Velvet Atlas', exact: true })).toBeVisible();
 await page.getByRole('link', { name: 'KIDS', exact: true }).click();
 await expect(page.getByRole('heading', { name: 'Velvet Atlas', exact: true })).toBeVisible();
 await page.reload();
 await expect(page.getByRole('heading', { name: 'Velvet Atlas', exact: true })).toBeVisible();
 expect(outgoing.join('\n')).not.toMatch(/Velvet|Unsaved Encore/);
});

test('Afterhours creates mascot and pasta names, supports remix and editing, and fits mobile', async ({ page }) => {
 const outgoing: string[] = [];
 page.on('request', request => outgoing.push(request.url() + (request.postData() || '')));
 await page.goto('/#advanced/name');
 await page.getByRole('button', { name: 'Create a name', exact: true }).click();
 const mascot = page.getByLabel('High school mascot'), pasta = page.getByLabel('Favorite type of pasta');
 const generate = page.getByRole('button', { name: 'Make my DJ name →', exact: true });
 await expect(generate).toBeDisabled();
 await mascot.fill('Falcon');
 await pasta.fill('   ');
 await expect(generate).toBeDisabled();
 await pasta.fill('Farfalle');
 await page.screenshot({ path: 'docs/evidence/experience/afterhours-name-ingredients.png' });
 await generate.click();
 await expect(page.getByRole('heading', { name: 'DJ Falcon Farfalle', exact: true })).toBeVisible();
 await page.getByRole('button', { name: '↻ Give me another' }).click();
 await expect(page.getByRole('heading', { name: 'DJ Farfalle Falcon', exact: true })).toBeVisible();
 await page.getByRole('button', { name: '← Back', exact: true }).click();
 await expect(mascot).toHaveValue('Falcon');
 await expect(pasta).toHaveValue('Farfalle');
 await pasta.fill('Rigatoni');
 await page.setViewportSize({ width: 390, height: 844 });
 expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
 await page.screenshot({ path: 'docs/evidence/experience/afterhours-name-ingredients-mobile.png', fullPage: true });
 await generate.click();
 await expect(page.getByRole('heading', { name: 'DJ Falcon Rigatoni', exact: true })).toBeVisible();
 expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
 await page.screenshot({ path: 'docs/evidence/experience/afterhours-name-reveal-mobile.png', fullPage: true });
 await page.getByRole('button', { name: 'Use this name →', exact: true }).click();
 await expect(page).toHaveURL(/#advanced\/session$/);
 await expect(page.getByRole('heading', { name: 'DJ Falcon Rigatoni', exact: true })).toBeVisible();
 await page.getByRole('button', { name: 'Change DJ name' }).click();
 await page.getByRole('button', { name: 'Create a name', exact: true }).click();
 await expect(mascot).toHaveValue('');
 await expect(pasta).toHaveValue('');
 await mascot.fill('Otter');
 await pasta.fill('Fusilli');
 await generate.click();
 await page.getByRole('button', { name: 'Edit this name', exact: true }).click();
 await expect(page.getByLabel('Your name or DJ name')).toHaveValue('DJ Otter Fusilli');
 await page.getByLabel('Your name or DJ name').fill('The Fusilli Sessions');
 await page.getByRole('button', { name: 'Continue to music →' }).click();
 await expect(page.getByRole('heading', { name: 'The Fusilli Sessions', exact: true })).toBeVisible();
 expect(outgoing.join('\n')).not.toMatch(/Falcon|Farfalle|Rigatoni|Otter|Fusilli/);
});

test('Kids and Afterhours share DJ identity, crate, playlist and browser navigation', async ({ page }) => {
 const errors: string[] = [], outgoing: string[] = [];
 page.on('pageerror', error => errors.push(error.message));
 page.on('request', request => outgoing.push(request.url() + (request.postData() || '')));
 await page.goto('/');
 await page.getByRole('link', { name: 'KIDS', exact: true }).click();
 await expect(page.getByRole('heading', { name: 'Make the music move.' })).toBeVisible();
 await page.screenshot({ path: 'docs/evidence/experience/kids-desktop.png' });
 await page.getByRole('button', { name: 'Create my DJ name →' }).click();
 await expect(page.getByRole('button', { name: 'Next →', exact: true })).toBeDisabled();
 await page.getByRole('textbox', { name: 'Your first name or nickname' }).fill('Testgroove');
 await page.getByRole('button', { name: 'Next →', exact: true }).click();
 await page.getByRole('button', { name: 'Fox', exact: true }).click();
 await page.getByRole('button', { name: 'Make my DJ name →', exact: true }).click();
 await expect(page.getByRole('heading', { name: 'DJ Fox Testgroove' })).toBeVisible();
 await page.getByRole('button', { name: '↻ Give me another' }).click();
 await expect(page.getByRole('heading', { name: 'DJ Testgroove Foxfunk' })).toBeVisible();
 await page.screenshot({ path: 'docs/evidence/experience/name-reveal.png' });
 await page.getByRole('button', { name: "That's me — let's go →" }).click();
 await expect(page).toHaveURL(/#kids\/session$/);
 await expect(page.getByRole('navigation',{name:'Music workflow'})).toHaveCount(0);
 await expect(page.getByLabel('Choose song A')).toHaveValue('amber');
 await page.getByRole('button',{name:'Play these songs →'}).click();
 await page.getByRole('link',{name:'♫ Choose songs',exact:true}).click();
 await page.getByRole('link', { name: 'Afterhours', exact: true }).click();
 await expect(page.getByRole('heading', { name: 'DJ Testgroove Foxfunk' })).toBeVisible();
 await expect(page.locator('.crate-list')).toContainText('2 / 12');
 await page.getByRole('navigation', { name: 'Music workflow' }).getByRole('button', { name: /Recommend/ }).click();
 await expect(page.locator('.pair-suggestion')).toContainText('120 → 120 BPM');
 await page.getByRole('button', { name: 'Add pair to playlist →' }).click();
 await page.getByRole('button', { name: 'Move Afterglow Steps up' }).click();
 await expect(page.locator('.playlist li').first()).toContainText('Afterglow Steps');
 await page.screenshot({ path: 'docs/evidence/experience/advanced-playlist.png' });
 await page.getByRole('link', { name: 'KIDS', exact: true }).click();
 await expect(page.getByLabel('Choose song A')).toHaveValue('afterglow');
 await page.goBack();
 await expect(page).toHaveURL(/#advanced\/session$/);
 await page.getByRole('button', { name: 'Load first two & open booth →' }).click();
 await expect(page).toHaveURL(/#advanced\/play$/);
 await expect(page.getByRole('article', { name: 'Deck A performance', exact: true }).getByRole('heading')).toHaveText('Afterglow Steps');
 await expect(page.locator('.waveform-traces canvas')).toHaveAttribute('data-ready', 'true');
 expect(outgoing.join('\n')).not.toContain('Testgroove');
 expect(errors).toEqual([]);
});

test('local crate import decodes real metadata and keeps unsupported preparation honest', async ({ page }) => {
 const posts: string[] = [];
 page.on('request', request => { if (request.method() === 'POST') posts.push(request.url()); });
 await page.goto('/#advanced/session');
 await expect(page.getByRole('button', { name: 'Choose music files' })).toBeEnabled();
 await page.getByLabel('Add music to crate').setInputFiles({name:'invalid.mp3',mimeType:'audio/mpeg',buffer:Buffer.from('not audio')});
 await expect(page.getByRole('alert')).toContainText('Could not read');
 await page.screenshot({path:'docs/evidence/experience/import-error.png'});
 await page.getByLabel('Add music to crate').setInputFiles('public/audio/amber.wav');
 await expect(page.locator('.crate-list')).toContainText('amber.wav');
 await page.getByRole('navigation', { name: 'Music workflow' }).getByRole('button', { name: /Analyze music/ }).click();
 await expect(page.locator('tbody')).toContainText('32.0s');
 await expect(page.locator('tbody').getByText('Unknown', { exact: true })).toHaveCount(2);
 await page.getByRole('navigation', { name: 'Music workflow' }).getByRole('button', { name: /Create stems/ }).click();
 await expect(page.locator('.stem-readiness')).toContainText('Original mix only · stems unavailable');
 await page.screenshot({ path: 'docs/evidence/experience/stems-unavailable.png' });
 await page.getByRole('navigation', { name: 'Music workflow' }).getByRole('button', { name: /Recommend/ }).click();
 await expect(page.getByText(/No close-tempo pair/)).toBeVisible();
 await page.getByRole('navigation', { name: 'Music workflow' }).getByRole('button', { name: /Upload music/ }).click();
 await page.getByRole('button', { name: 'Use demo tracks', exact: true }).click();
 await page.getByRole('navigation', { name: 'Music workflow' }).getByRole('button', { name: /Playlist/ }).click();
 await page.locator('.playlist-crate').getByRole('button', { name: '＋ amber.wav', exact: true }).click();
 await page.locator('.playlist-crate').getByRole('button', { name: '＋ Afterglow Steps', exact: true }).click();
 await page.getByRole('button', { name: 'Load first two & open booth →' }).click();
 await expect(page.getByRole('article', { name: 'Deck A performance', exact: true }).getByRole('heading')).toHaveText('amber.wav');
 await expect(page.getByRole('article', { name: 'Deck A performance', exact: true })).toContainText('Original mix · no prepared stems');
 await page.getByRole('button', { name: 'Start audio', exact: false }).click();
 await page.getByRole('article', { name: 'Deck A performance', exact: true }).getByRole('button', { name: '▶ Play A', exact: true }).click();
 await expect(page.getByRole('article', { name: 'Deck A performance', exact: true }).locator('output').first()).toContainText('playing');
 expect(posts).toEqual([]);
});

test('mode and preparation navigation retain the live mixer and uninterrupted captured output', async ({ page }) => {
 await page.goto('/#kids/play');
 await page.getByRole('button', { name: 'Turn on sound', exact: false }).click();
 await page.getByRole('article',{name:'Song A controls'}).getByRole('button',{name:'▶ Play A',exact:true}).click();
 await page.getByLabel('Song A sound',{exact:true}).fill('0.7');
 await page.getByRole('button', { name: 'Capture mix', exact: false }).click();
 const deckA = page.getByRole('article', { name: 'Deck A performance', exact: true });
 await page.waitForTimeout(700);
 const before = await page.getByLabel('Song A playback').textContent();
 await expect(page.getByLabel('Song A playback')).toContainText('Playing');
 await page.getByRole('link', { name: 'Afterhours', exact: true }).click();
 await page.getByRole('navigation', { name: 'Music workflow' }).getByRole('button', { name: /Analyze music/ }).click();
 // Performance shortcuts must not hijack navigation/naming screens.
 await page.keyboard.press('q');
 await page.getByRole('navigation', { name: 'Music workflow' }).getByRole('button', { name: /F Play/ }).click();
 await expect(page.getByLabel('Performance filter A', { exact: true })).toHaveValue('0.7');
 await expect(deckA.locator('output').first()).toContainText('playing');
 expect(before).toContain('Playing');
 expect(parseFloat((await deckA.locator('output').first().textContent())!)).toBeGreaterThan(.7);
 await expect(page.locator('.waveform-traces canvas')).toHaveAttribute('data-ready', 'true');
 await page.waitForTimeout(700);
 await page.getByRole('button', { name: 'Finish capture', exact: false }).click();
 const link = page.getByRole('link', { name: 'Save audio', exact: false });
 await expect(link).toBeVisible();
 const url = (await link.getAttribute('href'))!;
 const metrics = await page.evaluate(async url => {
  const context = new OfflineAudioContext(1, 24000, 24000);
  const audio = await context.decodeAudioData(await (await fetch(url)).arrayBuffer());
  const samples = audio.getChannelData(0); let energy = 0, silence = 0, longest = 0;
  for (let i = Math.floor(.5 * audio.sampleRate); i < samples.length; i++) { energy += samples[i] ** 2; silence = Math.abs(samples[i]) < .00001 ? silence + 1 : 0; longest = Math.max(longest, silence); }
  return { duration: audio.duration, rms: Math.sqrt(energy / samples.length), longestSilence: longest / audio.sampleRate };
 }, url);
 expect(metrics.rms).toBeGreaterThan(.01);
 expect(metrics.longestSilence).toBeLessThan(.1);
 await writeFile('docs/evidence/experience/navigation-audio.json', JSON.stringify(metrics, null, 2));
 const download = page.waitForEvent('download'); await link.click(); await (await download).saveAs('docs/evidence/experience/navigation-audio.webm');
 await page.getByRole('button', { name: 'Stop all decks', exact: false }).click();
});

test('Kids onboarding and the simplified song picker fit a small screen', async ({ page }) => {
 await page.setViewportSize({ width: 390, height: 844 });
 await page.goto('/#kids');
 await expect(page.getByRole('link', { name: 'Afterhours', exact: true })).toBeVisible();
 expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
 await page.screenshot({ path: 'docs/evidence/experience/kids-mobile.png', fullPage: true });
 await page.getByRole('button', { name: 'Create my DJ name →' }).click();
 await page.getByRole('button', { name: 'Skip for now →' }).click();
 await expect(page.getByLabel('Choose song A')).toBeVisible();
 await page.getByRole('button',{name:'Play these songs →'}).click();
 await page.getByRole('link',{name:'♫ Choose songs',exact:true}).click();
 expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
 await page.screenshot({ path: 'docs/evidence/experience/session-mobile.png', fullPage: true });
 await page.getByRole('link', { name: 'Afterhours', exact: true }).click();
 await expect(page.locator('.crate-list')).toContainText('2 / 12');
 expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
});

test('Kids discovers real sound with fewer controls and retains settings in Afterhours', async ({ page }) => {
 await page.goto('/#kids/session');
 await expect(page.getByRole('navigation',{name:'Music workflow'})).toHaveCount(0);
 await page.getByRole('button',{name:'Play these songs →'}).click();
 await expect(page.getByRole('slider',{name:'Tempo A',exact:true})).toHaveCount(0);
 await expect(page.getByRole('region',{name:'Transition practice'})).toHaveCount(0);
 await expect(page.getByRole('button',{name:'4 CDJs',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Turn on sound',exact:false}).click();
 await page.getByRole('button',{name:'Let’s try it →'}).click();
 await expect(page.getByRole('heading',{name:'Wake up a song.'})).toBeVisible();
 await page.getByRole('article',{name:'Song A controls'}).getByRole('button',{name:'▶ Play A',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Put a blanket on the sound.'})).toBeVisible();
 await page.getByRole('slider',{name:'Song A sound'}).fill('0.5');
 await expect(page.getByRole('heading',{name:'Let two worlds meet.'})).toBeVisible();
 await page.getByRole('article',{name:'Song B controls'}).getByRole('button',{name:'▶ Play B',exact:true}).click();
 await page.getByRole('slider',{name:'Mix the songs',exact:true}).fill('0.5');
 await expect(page.getByRole('heading',{name:'You made your first blend!'})).toBeVisible();
 await expect(page.locator('.kids-discoveries li[data-complete=true]')).toHaveCount(3);
 await page.screenshot({path:'docs/evidence/experience/kids-discoveries.png',fullPage:true});
 await page.getByRole('link',{name:'Afterhours',exact:true}).click();
 await expect(page.getByLabel('Performance filter A',{exact:true})).toHaveValue('0.5');
 await expect(page.getByLabel('Performance crossfader',{exact:true})).toHaveValue('0.5');
 await expect(page.getByRole('article',{name:'Deck A performance'})).toContainText('playing');
 await page.getByRole('link',{name:'KIDS',exact:true}).click();
 await expect(page.getByRole('heading',{name:'You made your first blend!'})).toBeVisible();
 await page.getByRole('button',{name:'Try the discoveries again',exact:false}).click();
 await expect(page.getByRole('heading',{name:'Wake up a song.'})).toBeVisible();
 await page.getByRole('button',{name:'Pause all songs',exact:false}).click();
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);
 await page.screenshot({path:'docs/evidence/experience/kids-play-mobile.png',fullPage:true});
});
