import { describe,it,expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { Session,TrackSchema,position,crossGains,cutoff } from '../src/domain/session';
const tracks=TrackSchema.array().parse(JSON.parse(readFileSync('public/audio/manifest.json','utf8')));
describe('shared commands and audio-clock source mapping',()=>{
 it('bounds controls, rejects malformed values and agent writes',()=>{const s=new Session(tracks);for(const value of [-1,1.01,NaN,Infinity])expect(s.apply({type:'gain',deck:'A',value},0)).toBeNull();expect(s.apply({type:'crossfader',value:1},0,'agent')).toBeNull();expect(s.decks.A.gain).toBe(.8);expect(s.crossfader).toBe(0);});
 it('deduplicates commands and records human provenance',()=>{const s=new Session(tracks);expect(s.apply({type:'play',deck:'A'},5,'pointer','same')).not.toBeNull();expect(s.apply({type:'play',deck:'A'},7,'pointer','same')).toBeNull();expect(s.history).toHaveLength(1);expect(s.owners['A.play']).toBe('pointer');expect(position(s.decks.A,8)).toBe(3);});
 it('pause/resume and cue preserve source position across loops',()=>{const s=new Session(tracks);s.apply({type:'play',deck:'A'},10);expect(position(s.decks.A,45)).toBe(3);s.apply({type:'pause',deck:'A'},45);expect(position(s.decks.A,90)).toBe(3);s.apply({type:'play',deck:'A'},90);expect(position(s.decks.A,92)).toBe(5);s.apply({type:'cue',deck:'A'},92);expect(position(s.decks.A,94)).toBe(0);expect(s.decks.A.playing).toBe(false);});
 it('has equal-power midpoint and isolated endpoints',()=>{expect(crossGains(0)[0]).toBe(1);expect(crossGains(1)[0]).toBeCloseTo(0);const [a,b]=crossGains(.5);expect(a*a+b*b).toBeCloseTo(1);expect(cutoff(0)).toBe(160);expect(cutoff(1)).toBe(20000);});
});
describe('practice evidence and checkpoint',()=>{
 it('completes only after a correctly timed B start and audible handoff',()=>{const s=new Session(tracks);s.apply({type:'retry'},100);expect(s.attempt.status).toBe('running');s.apply({type:'play',deck:'B'},108.1);s.apply({type:'crossfader',value:1},111);expect(s.attempt.status).toBe('complete');expect(s.attempt.entryError).toBeCloseTo(.1);});
 it('reports an early entry and expires a missed target without moving it',()=>{const s=new Session(tracks);s.apply({type:'retry'},0);s.apply({type:'play',deck:'B'},6);s.apply({type:'crossfader',value:1},10);expect(s.attempt.status).toBe('retry');expect(s.attempt.entryError).toBe(-2);s.apply({type:'retry'},20);s.evaluate(37);expect(s.attempt.status).toBe('retry');s.evaluate(100);expect(s.attempt.startedAt).toBe(20);});
 it('does not award a silent B handoff',()=>{const s=new Session(tracks);s.apply({type:'retry'},0);s.apply({type:'gain',deck:'B',value:0},2);s.apply({type:'play',deck:'B'},8);s.apply({type:'crossfader',value:1},12);expect(s.attempt.status).toBe('running');});
 it('restores identities, stems, filters, levels and audio-clock origin',()=>{const s=new Session(tracks);s.apply({type:'retry'},1);s.apply({type:'filter',deck:'A',value:0},2);s.apply({type:'stem',deck:'B',stem:'drums',enabled:false},3);s.apply({type:'crossfader',value:.5},4);s.apply({type:'retry'},100);expect(position(s.decks.A,101)).toBe(1);expect(position(s.decks.B,101)).toBe(0);expect(s.decks.A.gain).toBe(.8);expect(s.decks.A.filter).toBe(1);expect(s.decks.B.stems.drums).toBe(true);expect(s.crossfader).toBe(0);expect(s.attempt.checkpoint?.tracks).toEqual(tracks.map(t=>t.sha256));});
 it('transport changes invalidate an attempt and do not stop free play',()=>{const s=new Session(tracks);s.apply({type:'retry'},0);s.apply({type:'pause',deck:'A'},2);expect(s.attempt.status).toBe('retry');s.apply({type:'play',deck:'B'},3);expect(s.decks.B.playing).toBe(true);});
});
describe('four-channel operation',()=>{
 it('C and D retain independent source clocks, EQ and levels; stop and retry include all four',()=>{const s=new Session(tracks);s.apply({type:'play',deck:'C'},2);s.apply({type:'play',deck:'D'},5);s.apply({type:'eq',deck:'C',band:'low',value:-6},6);s.apply({type:'gain',deck:'D',value:.35},6);expect(position(s.decks.C,8)).toBe(6);expect(position(s.decks.D,8)).toBe(3);expect(s.decks.A.playing).toBe(false);expect(s.decks.D.eq.low).toBe(0);s.apply({type:'stop'},8);expect(position(s.decks.C,20)).toBe(6);expect(position(s.decks.D,20)).toBe(3);s.apply({type:'retry'},25);expect(s.decks.C.eq.low).toBe(0);expect(s.decks.D.gain).toBe(.8);expect(s.decks.C.playing).toBe(false);expect(s.decks.D.playing).toBe(false);expect(s.history.at(-1)?.positions).toEqual({A:0,B:0,C:0,D:0});});
 it('validates EQ and prevents extra-deck assistance from passing the A/B challenge',()=>{const s=new Session(tracks);expect(s.apply({type:'eq',deck:'D',band:'low',value:13},0)).toBeNull();s.apply({type:'retry'},1);s.apply({type:'play',deck:'C'},2);expect(s.attempt.status).toBe('retry');});
});
describe('rate, cues and real checkpoints',()=>{
 it('changes rate without moving source and preserves mapping through pause and seek',()=>{const s=new Session(tracks);s.apply({type:'play',deck:'A'},10);s.apply({type:'rate',deck:'A',value:1.1},12);expect(position(s.decks.A,12)).toBe(2);expect(position(s.decks.A,22)).toBeCloseTo(13);s.apply({type:'seek',deck:'A',position:6},22);expect(s.decks.A.playing).toBe(true);expect(position(s.decks.A,24)).toBeCloseTo(8.2);s.apply({type:'pause',deck:'A'},24);expect(position(s.decks.A,100)).toBeCloseTo(8.2);expect(s.apply({type:'rate',deck:'A',value:1.17},100)).toBeNull();expect(s.apply({type:'seek',deck:'A',position:32},100)).toBeNull();});
 it('refuses unverified exercise grids',()=>{const s=new Session(tracks);expect(()=>s.useLoadedExercise(0)).toThrow('Verify');});
 it('does not score nonexistent enabled stems as audible',()=>{const s=new Session(tracks);s.apply({type:'retry'},0);for(const stem of tracks[1].stems)s.apply({type:'stem',deck:'B',stem:stem.name,enabled:false},1);s.apply({type:'play',deck:'B'},8);s.apply({type:'crossfader',value:1},10);expect(s.attempt.status).toBe('running');});
 it('restores all checkpoint values after track replacement',()=>{const s=new Session(tracks);s.checkpoint.decks.A.offset=4;s.checkpoint.decks.A.rate=1.05;s.checkpoint.decks.B.eq.low=-6;s.checkpoint.decks.B.filter=.7;s.checkpoint.decks.B.stems.bass=false;s.decks.B.track=tracks[0];s.apply({type:'retry'},20);expect(position(s.decks.A,22)).toBeCloseTo(6.1);expect(s.decks.B.track.id).toBe(tracks[1].id);expect(s.decks.B.eq.low).toBe(-6);expect(s.decks.B.filter).toBe(.7);expect(s.decks.B.stems.bass).toBe(false);expect(s.attempt.assisted).toBe(false);});
});
describe('bounded audio-checked local exercise',()=>{
 const local=()=>tracks.map((t,i)=>({...t,duration:60,rhythmVerification:{start:2,end:22,method:'decoded-onsets' as const,medianOffsetSeconds:-.05,p90ErrorSeconds:.055,matchedBeats:40},rekordbox:{source:'rekordbox-xml' as const,trackId:String(i),exportSha256:'test',match:'test',alignmentVerified:false,bpm:120,key:'',grid:[{at:2,bpm:120,beat:1,meter:'4/4'}],marks:[]}}));
 it('accepts only a checked region and restores its nonzero source cues',()=>{const s=new Session(local());s.apply({type:'seek',deck:'A',position:2},0);s.apply({type:'seek',deck:'B',position:2},0);s.apply({type:'rate',deck:'A',value:1.1},0);s.useLoadedExercise(0);expect(s.exercise.entryAfter).toBeCloseTo(8/1.1);s.apply({type:'retry'},10);expect(position(s.decks.A,10)).toBe(2);s.apply({type:'play',deck:'B'},10+8/1.1);s.apply({type:'crossfader',value:1},20);expect(s.attempt.status).toBe('complete');s.apply({type:'rate',deck:'A',value:.9},21);s.apply({type:'retry'},30);expect(s.decks.A.rate).toBe(1.1);expect(position(s.decks.A,30)).toBe(2);});
 it('rejects starts outside the checked window or with excessive onset error',()=>{const s=new Session(local());s.apply({type:'seek',deck:'A',position:10},0);s.apply({type:'seek',deck:'B',position:2},0);expect(()=>s.useLoadedExercise(0)).toThrow('exceeds');s.apply({type:'seek',deck:'A',position:2},0);s.decks.A.track.rhythmVerification!.p90ErrorSeconds=.15;expect(()=>s.useLoadedExercise(0)).toThrow('exceeds');});
});
