import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { isLivingSleeveEnabled } from './camera/feature';
const LivingSleeve = import.meta.env.DEV ? lazy(() => import('./camera/LivingSleeve').then(module => ({ default: module.LivingSleeve }))) : null;
import { AudioEngine, getEngine } from './audio/engine';
import { createBooth, type Layout } from './scene/booth';
import { AskAstra } from './AskAstra';
import { AstraSession } from './AstraSession';
import { deckIds, TrackSchema, type Track, type Command, type Origin, type DeckId } from './domain/session';
import { Waveforms } from './Waveforms';
import { PerformanceControls } from './PerformanceControls';
import './style.css';
import './editorial-theme.css';
import { SiteHeader, Hero, Together, SiteFooter } from './PageFrame';
import { Experience, useExperienceRoute } from './experience/Experience';
import { KidsPlay } from './experience/KidsPlay';
import './afterhours-theme.css';
import type { CrateEntry } from './experience/crate';
function Booth({engine,send,layout,onGrab,onLoad}:{engine:AudioEngine;send:(c:Command,o?:Origin)=>void;layout:Layout;onGrab:(held:boolean)=>void;onLoad:(id:DeckId)=>void}){
 const host=useRef<HTMLDivElement>(null);const [hover,setHover]=useState('Drag a fader or filter. Click PLAY / CUE.');const [error,setError]=useState('');const [mixerStatus,setMixerStatus]=useState('Loading editable mixer · controls ready');const callback=useRef(send);callback.current=send;const loadCallback=useRef(onLoad);loadCallback.current=onLoad;
 useEffect(()=>{try{return createBooth(host.current!,engine,c=>callback.current(c,'pointer'),setHover,layout,onGrab,id=>loadCallback.current(id),setMixerStatus);}catch{setError('3D graphics unavailable. Use the accessible controls below.');}},[engine,layout,onGrab]);
 return <section className="stage"><div className="stage-note"><span className="dot"/> {layout==='vinyl'?'TWO TURNTABLES':layout==='digital4'?'FOUR DIGITAL PLAYERS':'TWO DIGITAL PLAYERS'} <span className="muted">/ {mixerStatus}</span></div><div ref={host} className="canvas-host"/><p className="stage-help">{error||hover}</p></section>;
}
export default function App(){
 const route=useExperienceRoute();
 const showBooth=!route||route.screen==='play';
 const kids=route?.audience==='kids';
 const [engine,setEngine]=useState<AudioEngine>();const [snap,setSnap]=useState<ReturnType<AudioEngine['snapshot']>>();const [error,setError]=useState('');const [ready,setReady]=useState(false);const [status,setStatus]=useState('Preparing original tracks…');const [astra,setAstra]=useState('Checking Astra…');const [available,setAvailable]=useState(false);const [sessionAvailable,setSessionAvailable]=useState(false);const [recording,setRecording]=useState(false);const [recordUrl,setRecordUrl]=useState('');const recorder=useRef<MediaRecorder|null>(null);const [details,setDetails]=useState(false);const [layout,setLayout]=useState<Layout>('digital4');const [digitalLayout,setDigitalLayout]=useState<Layout>('digital4');const [held,setHeld]=useState(false);
 const heldLayout=useRef<Layout>(layout);if(!held)heldLayout.current=kids?(layout==='vinyl'?'vinyl':'digital2'):layout;const surfaceLayout=heldLayout.current;
 const [loadingExercise,setLoadingExercise]=useState(false);const [practiceError,setPracticeError]=useState('');
 const [library,setLibrary]=useState<(Track&{status:string})[]>([]);const [loadingDeck,setLoadingDeck]=useState<DeckId|null>(null);
 useEffect(()=>{let active=true;const update=()=>fetch('/api/library').then(r=>r.json()).then(data=>{if(active&&Array.isArray(data.tracks))setLibrary(data.tracks.flatMap((t:unknown)=>{const parsed=TrackSchema.safeParse(t);return parsed.success?[{...parsed.data,status:(t as {status:string}).status}]:[];}));}).catch(()=>{});update();const timer=setInterval(update,15000);return()=>{active=false;clearInterval(timer);};},[]);
 async function chooseTrack(id:DeckId,value:string){if(!engine)return;const local=library.find(t=>t.id===value);try{setLoadingDeck(id);if(local)await engine.loadPrepared(id,local);else engine.loadFixture(id,value);setSnap(engine.snapshot());}catch(e){setError(e instanceof Error?e.message:'Track load failed');}finally{setLoadingDeck(null);}}
 const switchLayout=(next:Layout)=>{if(held)return;if(next!=='vinyl')setDigitalLayout(next);setLayout(next);};
 const toggleAlt=()=>switchLayout(layout==='vinyl'?digitalLayout:'vinyl');
 const openLibrary=(id:DeckId)=>{if(kids){location.hash='kids/session';return;}setDetails(true);requestAnimationFrame(()=>document.getElementById(`library-${id}`)?.scrollIntoView({block:'center',behavior:'auto'}));};
 useEffect(()=>{let active=true;getEngine().then(e=>{if(active){setEngine(e);setSnap(e.snapshot());setStatus('Tracks ready · audio not started');}}).catch(()=>setError('Could not prepare audio. Refresh to retry.'));
 fetch('/api/status').then(r=>r.json()).then(s=>{setAstra(s.message);setAvailable(s.available);setSessionAvailable(s.session?.available===true);}).catch(()=>setAstra('Astra unavailable · gateway offline'));
 return()=>{active=false;};},[]);
 useEffect(()=>{if(!engine)return;const timer=setInterval(()=>setSnap(engine.snapshot()),100);return()=>clearInterval(timer);},[engine]);
 const send=(c:Command,o:Origin='accessible')=>{if(!engine||!ready)return;try{engine.command(c,o);setSnap(engine.snapshot());}catch{setError('Audio command failed. Stop and retry.');}};
 useEffect(()=>{function key(e:KeyboardEvent){if(!showBooth)return;if(document.querySelector('dialog[open], [role="dialog"]'))return;if(e.target instanceof HTMLTextAreaElement||(e.target instanceof HTMLElement&&e.target.isContentEditable))return;if(!kids&&e.key==='Alt'&&!e.repeat){e.preventDefault();toggleAlt();return;}if(e.target instanceof HTMLTextAreaElement||(e.target instanceof HTMLElement&&e.target.isContentEditable)||e.target instanceof HTMLInputElement||e.target instanceof HTMLButtonElement||e.target instanceof HTMLSelectElement||e.ctrlKey||e.metaKey||e.altKey||e.repeat)return;if(!engine||!ready)return;
 const key=e.key.toLowerCase(),map:Record<string,Command>={e:{type:engine.session.decks.C.playing?'pause':'play',deck:'C'},i:{type:engine.session.decks.D.playing?'pause':'play',deck:'D'},q:{type:engine.session.decks.A.playing?'pause':'play',deck:'A'},p:{type:engine.session.decks.B.playing?'pause':'play',deck:'B'},w:{type:'cue',deck:'A'},o:{type:'cue',deck:'B'},r:{type:'retry'},' ':{type:'stop'},arrowleft:{type:'crossfader',value:Math.max(0,engine.session.crossfader-0.05)},arrowright:{type:'crossfader',value:Math.min(1,engine.session.crossfader+0.05)}};
 if(kids&&['e','i','r','w','o'].includes(key))return;
 if(map[key]){e.preventDefault();send(map[key],'keyboard');}}
 window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
 async function start(){if(!engine)return;try{await engine.resume();setReady(true);setStatus('Audio running · shared four-channel mixer');}catch{setError('Audio start was blocked. Try Start audio again.');}}
 function record(){if(!engine)return;if(recording){recorder.current?.stop();setRecording(false);return;}if(!('MediaRecorder'in window)){setError('Mix capture is unsupported in this browser.');return;}const chunks:Blob[]=[];const rec=new MediaRecorder(engine.capture.stream);rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=()=>{if(recordUrl)URL.revokeObjectURL(recordUrl);setRecordUrl(URL.createObjectURL(new Blob(chunks,{type:rec.mimeType})));};rec.start();recorder.current=rec;setRecording(true);}
 async function loadJourneyPair(entries:CrateEntry[]){
  if(!engine)throw new Error('The booth is still preparing. Try again in a moment.');
  for(const [index,id] of (['A','B'] as const).entries()){
   const entry=entries[index];setLoadingDeck(id);
   try{if(entry.file)await engine.importTrack(id,entry.file);else if(engine.session.fixtures.some(t=>t.id===entry.track.id))engine.loadFixture(id,entry.track.id);else await engine.loadPrepared(id,entry.track);
    if(engine.session.decks[id].track.id!==entry.track.id)throw new Error('Another track load took over. Check your decks before retrying.');
   }finally{setLoadingDeck(null);setSnap(engine.snapshot());}
  }
 }
 return <main data-experience={kids?'kids':'advanced'} className={kids?'kids-site':'afterhours-site'}>
 <SiteHeader route={route}/>{(!route||(route.audience==='advanced'&&route.screen==='landing'))&&<Hero/>}
 <Experience route={route} engine={engine} library={library} onLoadPair={loadJourneyPair}/>
 <section hidden={!showBooth} className="performance-shell" id="play" aria-label="Playable booth"><div hidden={kids} className="play-intro"><div><p className="eyebrow">02 / FIND YOUR FEEL</p><h2>The best way in?<br/><em>Play a little.</em></h2></div><div className="audio-start"><p>Start the sound. Find two grooves.<br/>Switch the setup without stopping the music.</p><button className="primary" disabled={!engine} onClick={start}>{ready?'✓ Audio enabled':'↗ Start audio'}</button><small>{status}</small></div></div>
 {error&&<p role="alert" className="error">{error}</p>}
 {LivingSleeve&&isLivingSleeveEnabled(import.meta.env.DEV,location.search)&&<Suspense fallback={null}><LivingSleeve/></Suspense>}
 {engine&&snap&&<KidsPlay engine={engine} snapshot={snap} ready={ready} active={kids&&showBooth} onStart={start} send={send}/>}
 {kids&&<div className="kids-real-decks"><div><p>TRY THE REAL DECKS</p><h2>Big buttons. Real sound.</h2></div><nav aria-label="Kids equipment"><button disabled={held} aria-pressed={surfaceLayout!=='vinyl'} onClick={()=>switchLayout('digital2')}>◉ Players</button><button disabled={held} aria-pressed={surfaceLayout==='vinyl'} onClick={()=>switchLayout('vinyl')}>◎ Records</button></nav></div>}
 <nav hidden={kids} className="rig-selector" aria-label="Equipment layout"><div><span className="eyebrow">YOUR SETUP</span><button aria-pressed={layout==='digital2'} disabled={held} onClick={()=>switchLayout('digital2')}>2 CDJs</button><button aria-pressed={layout==='digital4'} disabled={held} onClick={()=>switchLayout('digital4')}>4 CDJs</button><button aria-pressed={layout==='vinyl'} disabled={held} onClick={toggleAlt}>ALT · 2 turntables</button></div><span>{held?'Release the control to switch.':layout==='vinyl'?'Vinyl surface · A / B · same live mix':layout==='digital4'?'Digital players · A / B / C / D left to right':'Digital players · A / B'}</span></nav>
 <div hidden={kids}>{engine&&<Waveforms engine={engine} layout={surfaceLayout}/>}</div>
 {engine?<Booth engine={engine} send={send} layout={surfaceLayout} onGrab={setHeld} onLoad={openLibrary}/>:<div className="loading">Preparing the booth…</div>}
 {!kids&&layout!=='digital4'&&snap&&<div className="retained-decks"><span>C / D retained in the mixer</span>{(['C','D'] as const).map(id=><button key={id} disabled={!ready} onClick={()=>send({type:snap.decks[id].playing?'pause':'play',deck:id})}>{snap.decks[id].playing?'Pause':'Play'} {id} · {snap.decks[id].position.toFixed(1)}s</button>)}<button onClick={()=>openLibrary('C')}>C / D library & levels ↗</button></div>}
 {!kids&&snap?.attempt.status==='running'&&engine&&<div className="exercise-live" aria-label="Live handoff controls"><strong>{Math.max(0,engine.context.currentTime-snap.attempt.startedAt).toFixed(1)}s / {snap.exercise.endAfter.toFixed(1)}s</strong><span>{engine.context.currentTime-snap.attempt.startedAt<snap.exercise.entryAfter?`B in ${(snap.exercise.entryAfter-engine.context.currentTime+snap.attempt.startedAt).toFixed(1)}s`:'Blend to B →'}</span><button disabled={snap.decks.B.playing} onClick={()=>send({type:'play',deck:'B'})}>{snap.decks.B.playing?'B is playing':'Enter B · P'}</button><label>Blend<input aria-label="Practice blend" type="range" min="0" max="1" step="0.01" value={snap.crossfader} onChange={e=>send({type:'crossfader',value:+e.target.value})}/></label></div>}
 {!kids&&snap&&<PerformanceControls snapshot={snap} ready={ready} send={send} onLoad={openLibrary}/>}
 <section hidden={kids} className={`practice ${snap?.attempt.status==='complete'?'complete':''}`} aria-label="Transition practice"><div className="practice-number">01</div><div className="practice-copy"><p className="eyebrow">THE FIRST HANDOFF <span>{snap?.exercise.provenance}</span></p><h2>{snap?.exercise.title||'Choose your handoff.'}</h2><p>{snap?`Start B at ${snap.exercise.entryAfter.toFixed(2)} seconds. Complete the blend by ${snap.exercise.endAfter.toFixed(2)} seconds.`:'Preparing exercise…'}</p><p aria-live="polite">{snap?.attempt.observation||'Prepare a pair, then start practice.'}</p>{snap?.attempt.status==='running'&&<div className="practice-timing"><span className="practice-clock">{Math.max(0,engine!.context.currentTime-snap.attempt.startedAt).toFixed(1)}s elapsed · {engine!.context.currentTime-snap.attempt.startedAt<snap.exercise.entryAfter?`${Math.max(0,snap.exercise.entryAfter-engine!.context.currentTime+snap.attempt.startedAt).toFixed(1)}s to B`:'Fade to B →'}</span><div className="progress"><span style={{width:`${Math.min(100,(engine!.context.currentTime-snap.attempt.startedAt)/snap.exercise.endAfter*100)}%`}}/><i style={{left:`${snap.exercise.entryAfter/snap.exercise.endAfter*100}%`}}/></div></div>}<div className="practice-config"><button disabled={!ready||loadingExercise} onClick={async()=>{setLoadingExercise(true);try{await engine!.loadExercisePair();setPracticeError('');setSnap(engine!.snapshot());}catch(e){setPracticeError(e instanceof Error?e.message:'Could not load prepared exercise');}finally{setLoadingExercise(false);}}}>{loadingExercise?'Loading prepared pair…':'Load prepared exercise'}</button><button disabled={!ready||loadingExercise} onClick={()=>{try{engine!.useLoadedExercise();setPracticeError('');setSnap(engine!.snapshot());}catch(e){setPracticeError(e instanceof Error?e.message:'Could not prepare this pair');}}}>Use loaded pair</button><button disabled={!ready||loadingExercise} onClick={()=>{try{engine!.useFixtureExercise();setPracticeError('');setSnap(engine!.snapshot());}catch(e){setPracticeError(e instanceof Error?e.message:'Could not restore fixture practice');}}}>Fixture practice</button></div>{practiceError&&<p role="alert" className="error">{practiceError}</p>}</div><button className="secondary" disabled={!ready} onClick={()=>send({type:'retry'})}>{snap?.attempt.status==='idle'?'Start practice':'↻ Retry practice'}</button></section>
 {engine&&<AskAstra engine={engine} available={available} status={astra} kidFriendly={kids}/>}
 {engine&&snap&&sessionAvailable&&<AstraSession engine={engine} snap={snap}/>}
 <div className="under-booth"><div className="session-actions"><button disabled={!ready} onClick={()=>send({type:'stop'})}>■ Stop all decks</button><button disabled={!ready} onClick={record}>{recording?'● Finish capture':'○ Capture mix'}</button>{recordUrl&&<a href={recordUrl} download="mixtape-session.webm">Save audio ↗</a>}</div></div>
 <section hidden={kids} className="control-section"><button className="control-toggle" aria-expanded={details} onClick={()=>setDetails(!details)}>{details?'−':'+'} Track library & accessible controls <span>Same instrument, every input.</span></button>{details&&snap&&<div className="accessible-controls">
 {deckIds.map(id=><div className="deck-controls" id={`library-${id}`} key={id}><h3>Deck {id} <span>{snap.decks[id].track.title}</span></h3><p>{snap.decks[id].track.rekordbox?`Rekordbox · ${snap.decks[id].track.bpm} BPM · ${snap.decks[id].track.rekordbox!.key||'key unknown'} · ${snap.decks[id].track.rekordbox!.marks.length} cue/loop markers · alignment unverified`:snap.decks[id].track.provenance}</p><output aria-label={`Deck ${id} position`}>{snap.decks[id].position.toFixed(2)} s · {snap.decks[id].playing?'playing':'paused'}</output><label className="track-picker">{layout==='vinyl'&&(id==='A'||id==='B')?'Record crate':'Digital library'}<select aria-label={`Track for ${id}`} disabled={!ready||loadingDeck!==null} value={snap.decks[id].track.id} onChange={e=>void chooseTrack(id,e.target.value)}>{snap.decks[id].track.id.startsWith('local-')&&!library.some(t=>t.id===snap.decks[id].track.id)&&<option value={snap.decks[id].track.id}>{snap.decks[id].track.title}</option>}{engine!.session.fixtures.map(t=><option key={t.id} value={t.id}>{t.title} · 120 BPM</option>)}{library.map(t=><option key={t.id} value={t.id}>{t.title} · {t.status==='stems-ready'?'4 stems ready':t.status==='running'?'preparing stems':t.status==='failed'?'original · stems failed':'original'}</option>)}</select>{loadingDeck===id&&<small>Loading local audio… current playback continues</small>}</label><div className="button-row">{library.some(t=>t.id===snap.decks[id].track.id)&&<button disabled={!ready||loadingDeck!==null} onClick={()=>void chooseTrack(id,snap.decks[id].track.id)}>Reload prepared version {id}</button>}<button disabled={!ready} onClick={()=>send({type:snap.decks[id].playing?'pause':'play',deck:id})}>{snap.decks[id].playing?'Pause':'Play'} {id}</button><button disabled={!ready} onClick={()=>send({type:'cue',deck:id})}>Cue {id}</button><label className="file-label">{layout==='vinyl'&&(id==='A'||id==='B')?'Load vinyl audio':'Load local audio'}<input aria-label={`Load deck ${id}`} type="file" accept="audio/*" disabled={!ready} onChange={async e=>{const file=e.target.files?.[0];if(file)try{await engine!.importTrack(id,file);setSnap(engine!.snapshot());}catch(err){setError(err instanceof Error?err.message:'Import failed');}e.target.value='';}}/></label></div>
 <label>Level {id} <output>{Math.round(snap.decks[id].gain*100)}%</output><input aria-label={`Level ${id}`} disabled={!ready} type="range" min="0" max="1" step="0.01" value={snap.decks[id].gain} onChange={e=>send({type:'gain',deck:id,value:+e.target.value})}/></label><label>Filter {id} <output>{snap.decks[id].filter===1?'Open':'Low-pass'}</output><input aria-label={`Filter ${id}`} disabled={!ready} type="range" min="0" max="1" step="0.01" value={snap.decks[id].filter} onChange={e=>send({type:'filter',deck:id,value:+e.target.value})}/></label><div className="eq-controls">{(['low','mid','high'] as const).map(band=><label key={band}>{band.toUpperCase()} <output>{snap.decks[id].eq[band].toFixed(1)} dB</output><input type="range" aria-label={`${band} EQ ${id}`} min="-12" max="12" step="0.5" disabled={!ready} value={snap.decks[id].eq[band]} onChange={e=>send({type:'eq',deck:id,band,value:+e.target.value})}/></label>)}</div><div className="stems">{snap.decks[id].track.stems.length>0?snap.decks[id].track.stems.map(({name:stem})=><label key={stem}><input type="checkbox" disabled={!ready} checked={snap.decks[id].stems[stem]} onChange={e=>send({type:'stem',deck:id,stem,enabled:e.target.checked})}/>{stem}</label>):'Original mix only · no prepared stems'}</div></div>)}<label className="cross-control">Crossfader <output>{Math.round(snap.crossfader*100)}% B</output><input aria-label="Crossfader" disabled={!ready} type="range" min="0" max="1" step="0.01" value={snap.crossfader} onChange={e=>send({type:'crossfader',value:+e.target.value})}/></label></div>}</section>
 <p hidden={kids} className="rig-disclosure">{layout==='vinyl'?'Vinyl loads audio from the record crate or your local files. Tonearm and platter are visual; scratching is not implemented. Tempo changes pitch; no key lock.':'Four independent decks; two original demo tracks are reused on C / D. Jog wheels show transport; scratching is not implemented. Tempo changes pitch; no key lock.'}</p><div hidden={kids} className="keyboard-footer"><p><kbd>ALT</kbd> swap rig <kbd>E / I</kbd> C / D play <kbd>Q</kbd> A play <kbd>W</kbd> A cue <kbd>P</kbd> B play <kbd>O</kbd> B cue <kbd>← →</kbd> blend <kbd>R</kbd> retry <kbd>SPACE</kbd> stop</p><span>Original synthesis · fixture-known grid · editable mixer / provisional players</span></div>
 <div className="mini-proof"><h3>Change the look.<br/>Keep the feeling.</h3><p>Digital players or turntables. Your tracks, blend, stems, and playback position stay yours.</p><span aria-hidden="true">〰〰〰</span></div></section>
 <section hidden={!!route} className="assist-section" id="assist"><div className="assist-copy"><p className="eyebrow">03 / A LITTLE BACKUP</p><h2>Your taste.<br/><em>Your call.</em></h2><p>One focused observation. One next move. Ask Astra for a hint, and keep the controls in your hands.</p><small>Hints use the current deck state. Astra never moves the mixer.</small></div><div className="assist-card"><p className="eyebrow">ASTRA / BACKSTAGE</p><h3>The next move<br/>is yours.</h3><p>Voice, text, and small prompts. One shared musical brief, with every control still yours.</p><a href="#ask-astra">Ask beside the decks ↗</a></div><div className="assist-values"><article><span>01 /</span><h3>Prepare, then play.</h3><p>Load local tracks and validated stems. Your music stays on this machine; BPM and key analysis are still to come.</p></article><article><span>02 /</span><h3>Room to change.</h3><p>Switch the setup, shape the sound, and follow your own direction. Every control belongs to you.</p></article><article><span>03 /</span><h3>Find that moment.</h3><p>Try the handoff practice, inspect its timing, then reset to the same starting point and try again.</p></article></div></section>
 {!route&&<Together/>}<SiteFooter compact={!!route}/>
 </main>;
}
